// /home/krylon/go/src/github.com/blicero/guangng/blacklist/default.go
// -*- mode: go; coding: utf-8; -*-
// Created on 12. 01. 2026 by Benjamin Walkenhorst
// (c) 2026 Benjamin Walkenhorst
// Time-stamp: <2026-01-12 15:12:10 krylon>

package blacklist

// This files contains the default lists of blacklisted names and IP ranges.

var defaultNamePatterns = []string{
	"\\bdiu?p-?\\d*\\.",
	"(?:versanet|telekom|uni-paderborn|upb)\\.(?:de|net|com|biz|eu)\\.?$",
	"[.]?nothing[.]",
	"[.]example[.](?:org|net|com)[.]?$",
	"[avs]?dsl",
	"\\.in-addr\\.",
	"\\.invalid\\.?",
	"\\b(?:wireless|wlan|wimax|wan|vpn|vlan)",
	"\\b\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3}\\b",
	"\\bincorrect(?:ly)?\\b",
	"\\bnot.configured\\b",
	"\\bpools?\\b",
	"\\bunn?ass?igned\\b",
	"^(?:client|host)(?:-?\\d+)?",
	"^(?:un|not-)(?:known|ass?igned|alloc(?:ated)?|registered|provisioned|used|defined|delegated)",
	"^[.]$",
	"^[*]",
	"^\\w*eth(?:ernet)[^.]*\\.",
	"^\\w\\d+\\[\\-.]",
	"^customer-",
	"^customer\\.",
	"^dyn\\d+",
	"^generic-?host",
	"^h\\d+s\\d+",
	"^host\\d+\\.",
	"^illegal",
	"^internal-host",
	"^ip(?:-?\\d+|addr)",
	"^mobile",
	"^no(?:-reverse)?-dns",
	"^(?:no-?)?reverse",
	"^no.ptr",
	"^softbank\\d+\\.bbtec",
	"^this.ip",
	"^user-?\\d+\\.",
	"aol\\.com\\.?$",
	"cable",
	"dhcp",
	"dial-?(?:in|up)?",
	"dyn(?:amic)?[-.0-9]",
	"dyn(?:amic)ip",
	"early.registration",
	"(?:edu)?roam",
	"localhost",
	"myvzw\\.com",
	"no-dns(?:-yet)?",
	"non-routed",
	"ppp",
	"rr\\.com\\.?$",
	"umts",
	"wanadoo\\.[a-z]{2,3}\\.?$",
	"^\\w*[.]$",
	"reverse-not-set",
	"uu[.]net[.]?$",
	"(?:ne|ad)[.]jp[.]?$",
	"[.](?:cn|mil)[.]?$",
	"^noname[.]",
}

var defaultNetworks = []string{
	"0.0.0.0/8",
	"10.0.0.0/8",
	"127.0.0.0/8",
	"169.254.0.0/16",
	"172.16.0.0/12",
	"192.0.2.0/24",
	"192.88.99.0/24",
	"192.168.0.0/16",
	"198.18.0.0/15",
	"198.51.100.0/24",
	"203.0.113.0/24",
	"224.0.0.0/4",
	"240.0.0.0/4",
	"255.0.0.0/8",
}
